name: Build and deploy Node.js app to Azure Web App - kavya-mern-api-001

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install
        working-directory: ./server   # 👈 IMPORTANT FIX

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./server   # 👈 deploy only backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_578CB3ADC31E4594960A487DA1997E85 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1E7F50CE80DA4BF59E7BABF54856B1EA }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_58D000253B4F40849CCBDD9A3DFD8154 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'kavya-mern-api-001'
          slot-name: 'Production'
          package: .
